= vim-iced

+++
<h4 align="center">
  <img src="logo.svg" alt="logo" /><br />
  Clojure Interactive Development Environment for Vim8/Neovim.
</h4>
<p align="center">
  <a href="https://github.com/liquidz/vim-iced/releases">
    <img src="https://img.shields.io/github/release/liquidz/vim-iced.svg" alt="GitHub release" />
  </a>
  <a href="https://circleci.com/gh/liquidz/vim-iced">
    <img src="https://img.shields.io/circleci/project/github/liquidz/vim-iced/master.svg" alt="CircleCI" />
  </a>
  <a href="https://codecov.io/gh/liquidz/vim-iced">
    <img src="https://codecov.io/gh/liquidz/vim-iced/branch/master/graph/badge.svg" alt="Codecov" />
  </a>
  <a href="https://github.com/liquidz/vim-iced/blob/master/LICENSE">
    <img src="https://img.shields.io/github/license/liquidz/vim-iced.svg" alt="GitHub license" />
  </a>
  <a href="https://github.com/vim-jp/vital.vim">
    <img src="https://img.shields.io/badge/powered%20by-vital.vim-80273f.svg" alt="Powered by vital.vim" />
  </a>
</p>
<p align="center">
  <img src="https://img.shields.io/badge/status-WORK%20IN%20PROGRESS-red.svg" alt="Work in progress" />
</p>
+++

== Requirements

 * Vim 8.1 or later, Neovim 0.3.1 or later
 ** Neovim support is *VERY EXPERIMENTAL*
 * Clojure 1.8 or later
 ** 1.9 or later is recommended
 * No python! (boost possible with `if_python3`)

== Features

[cols="2*,a"]
|===

|:zap:
|Asynchronous evaluation
|powered by `channel` in Vim8

|:fire:
|Testing
|[%hardbreaks]
run test under cursor
run tests in namespace
re run failed/last test

|:rocket:
|Refactoring
|[%hardbreaks]
clean namespace
add missing
thread first/last
extract function
move to let

|:mag:
|Reference
|Docs, Javadoc, and https://www.conj.io[Grimoire]

|:ant:
|Debugging
|supports cider-nrepl's debugger
https://twitter.com/uochan/status/1034404572368842752[:movie_camera:]

|:eyes:
|Linting
|powered by https://github.com/jonase/eastwood[jonase/eastwood]
https://twitter.com/uochan/status/1038050122062413824[:movie_camera:]
and https://github.com/candid82/joker[joker]

|:notebook:
|Skeleton
|provides code skeleton when you open new file

|:tophat:
|ClojureScript support
|`figwheel`, `graaljs` and `nashorn` is supported currently

|:art:
|Command palette
|access commands smoothly and define user custom commands

|===

NOTE: vim-iced is heavily powered by https://github.com/clojure-emacs/cider-nrepl[cider-nrepl],
https://github.com/clojure-emacs/refactor-nrepl[refactor-nrepl],
and https://github.com/liquidz/iced-nrepl[iced-nrepl].

== Installation

=== vim-plug

[source,vim]
----
" One of following is required
Plug 'ctrlpvim/ctrlp.vim'
" or
Plug 'junegunn/fzf'

Plug 'guns/vim-sexp',    {'for': 'clojure'}
Plug 'liquidz/vim-iced', {'for': 'clojure'}
----

NOTE: https://github.com/ctrlpvim/ctrlp.vim[ctrlp.vim] or https://github.com/junegunn/fzf[fzf] is required when selecting multiple candidates.

=== iced command (recommended)

* Add `$PATH` environment variable to link:./bin/iced[`/path/to/vim-iced/bin`].

`iced` command currently supports:

* Leiningen
* Boot
* Clojure CLI

=== Manual setting (not recommended)

* See `Manual Install` section in link:./doc/vim-iced.txt[vim-iced.txt].

== Usage

. Start repl via `iced` command
** `iced repl`
. Open source file
. Evaluate forms (If not connected, vim-iced will connect automatically)

== Configuration

=== key mappings

vim-iced is providing default key mappings.
To enable default key mappings, add following line to your `.vimrc`.

[source,vim]
----
let g:iced_enable_default_key_mappings = v:true
----

See `Customizing` section in link:./doc/vim-iced.txt[vim-iced.txt] for actual mappings.

== Document

  * See link:./doc/vim-iced.txt[vim-iced.txt].

== External plugins

 * https://github.com/liquidz/vim-iced-project-namespaces[vim-iced-project-namespaces]
 ** Provides `:IcedBrowseNamespace` command for jumping to namespace in your project.
 * https://github.com/liquidz/vim-iced-function-list[vim-iced-function-list]
 ** Provides `:IcedBrowseFunction` command for jumping to functions in current namespace.

== License

Copyright (c) 2018 http://twitter.com/uochan[Masashi Iizuka]

Distributed under the MIT License.
