= vim-iced

+++
<h4 align="center">
  <img src="logo.svg" alt="logo" /><br />
  Clojure Interactive Development Environment for Vim8/Neovim.
</h4>
<p align="center">
  <a href="https://github.com/liquidz/vim-iced/releases">
    <img src="https://img.shields.io/github/release/liquidz/vim-iced.svg?logo=Clojure&logoColor=white" alt="GitHub release" />
  </a>
  <a href="https://github.com/liquidz/vim-iced/blob/master/LICENSE">
    <img src="https://img.shields.io/github/license/liquidz/vim-iced.svg?logo=Github" alt="GitHub license" />
  </a>
  <a href="https://www.patreon.com/uochan">
    <img src="https://img.shields.io/badge/patreon-donate-yellow.svg?logo=Patreon" alt="Become a Patron" />
  </a>
  <a href="https://github.com/vim-jp/vital.vim">
    <img src="https://img.shields.io/badge/powered%20by-vital.vim-80273f.svg?logo=Vim" alt="Powered by vital.vim" />
  </a>
  <br />
  <a href="https://circleci.com/gh/liquidz/vim-iced">
    <img src="https://img.shields.io/circleci/project/github/liquidz/vim-iced/master.svg?logo=CircleCI" alt="CircleCI" />
  </a>
  <a href="https://codecov.io/gh/liquidz/vim-iced">
    <img src="https://codecov.io/gh/liquidz/vim-iced/branch/master/graph/badge.svg" alt="Codecov" />
  </a>
</p>
+++

== Requirements

 * Vim 8.1 or later, Neovim 0.3.2 or later.
 * Clojure 1.8 or later.
 ** 1.10 or later is recommended.
 * No python! (boost possible with `if_python3`)

== Features

[cols="2*,a"]
|===

|:zap:
|Asynchronous evaluation
|powered by `channel` in Vim8

|:fire:
|Testing
|[%hardbreaks]
Run test under cursor
Run tests in namespace
Re run failed/last test

|:rocket:
|Refactoring
|[%hardbreaks]
Clean namespace
Add missing
Thread first/last
Extract function
Move to let

|:mag:
|Reference
|Docs, Javadoc, and https://clojuredocs.org[ClojureDocs]

|:ant:
|Debugging
|Supports cider-nrepl's debugger
https://twitter.com/uochan/status/1034404572368842752[:movie_camera:]

|:eyes:
|Linting
|Powered by https://github.com/jonase/eastwood[jonase/eastwood]
https://twitter.com/uochan/status/1038050122062413824[:movie_camera:]
and https://github.com/candid82/joker[joker]

|:notebook:
|Skeleton
|Provides code skeleton when you open new file

|:tophat:
|ClojureScript support
|[%hardbreaks]
Supports followings currently.
- https://github.com/bhauman/figwheel-main[Figwheel Main], https://github.com/bhauman/lein-figwheel[lein-figwheel]
- https://github.com/thheller/shadow-cljs[shadow-cljs]
- https://github.com/graalvm/graaljs[GraalJS]
- Nashorn

|:art:
|Command palette
|Access commands smoothly and define user custom commands

|===

NOTE: vim-iced is heavily powered by https://github.com/clojure-emacs/cider-nrepl[cider-nrepl],
https://github.com/clojure-emacs/refactor-nrepl[refactor-nrepl],
and https://github.com/liquidz/iced-nrepl[iced-nrepl].

== Installation

=== vim-plug

[source,vim]
----
" One of following is required
Plug 'ctrlpvim/ctrlp.vim'
" or
Plug 'junegunn/fzf'

Plug 'guns/vim-sexp',    {'for': 'clojure'}
Plug 'liquidz/vim-iced', {'for': 'clojure'}
----

NOTE: https://github.com/ctrlpvim/ctrlp.vim[ctrlp.vim] or https://github.com/junegunn/fzf[fzf] is required when selecting multiple candidates.

=== iced command (recommended)

* Add `$PATH` environment variable to link:./bin/iced[`/path/to/vim-iced/bin`].

`iced` command currently supports:

* Leiningen
* Boot
* Clojure CLI

=== Manual setting (not recommended)

* See link:https://liquidz.github.io/vim-iced/vim-iced.html#vim-iced-install-manually[manual install] section in vim-iced.txt.
** To work with https://github.com/thheller/shadow-cljs[shadow-cljs], you need to set up manually.

== Usage

. Start repl via `iced` command.
** `iced repl`
. Open source file.
. Evaluate forms. (If not connected, vim-iced will connect automatically)

== Configuration

=== key mappings

vim-iced is providing default key mappings.
To enable default key mappings, add following line to your `.vimrc`.

[source,vim]
----
let g:iced_enable_default_key_mappings = v:true
----

See link:https://liquidz.github.io/vim-iced/vim-iced.html#vim-iced-customizing[customizing section] in vim-iced.txt for actual mappings.

== Document

  * See link:https://liquidz.github.io/vim-iced/vim-iced.html[vim-iced.txt].

== External plugins

 * https://github.com/liquidz/vim-iced-kaocha[vim-iced-kaocha]
 ** Provices some commands for testing with https://github.com/lambdaisland/kaocha[kaocha].
 * https://github.com/liquidz/vim-iced-project-namespaces[vim-iced-project-namespaces]
 ** Provides `:IcedBrowseNamespace` command for jumping to namespace in your project.
 * https://github.com/liquidz/vim-iced-function-list[vim-iced-function-list]
 ** Provides `:IcedBrowseFunction` command for jumping to functions in current namespace.

== License

Copyright (c) 2018-2019 http://twitter.com/uochan[Masashi Iizuka]

Distributed under the MIT License.
