= vim-iced

+++
<h4 align="center">
  <img src="doc/pages/assets/logo.svg" alt="logo" /><br />
  Clojure Interactive Development Environment for Vim8/Neovim.
</h4>
<p align="center">
  <a href="https://github.com/liquidz/vim-iced/releases">
    <img src="https://img.shields.io/github/release/liquidz/vim-iced.svg?logo=Clojure&logoColor=white" alt="GitHub release" />
  </a>
  <a href="https://github.com/liquidz/vim-iced/blob/master/LICENSE">
    <img src="https://img.shields.io/github/license/liquidz/vim-iced.svg?logo=Github" alt="GitHub license" />
  </a>
  <a href="https://github.com/vim-jp/vital.vim">
    <img src="https://img.shields.io/badge/powered%20by-vital.vim-80273f.svg?logo=Vim" alt="Powered by vital.vim" />
  </a>
  <br />
  <a href="https://github.com/liquidz/vim-iced/actions?query=workflow%3Avim%2Fneovim">
    <img src="https://github.com/liquidz/vim-iced/workflows/vim%2Fneovim/badge.svg" alt="GitHub Actions for vim/neovim workflow" />
  </a>
  <a href="https://github.com/liquidz/vim-iced/actions?query=workflow%3Adependencies">
    <img src="https://github.com/liquidz/vim-iced/workflows/dependencies/badge.svg" alt="GitHub Actions for dependencies workflow" />
  </a>
  <a href="https://codecov.io/gh/liquidz/vim-iced">
    <img src="https://codecov.io/gh/liquidz/vim-iced/branch/master/graph/badge.svg" alt="Codecov" />
  </a>
</p>
+++

== Requirements

 * Vim 8.1.0614 or later, Neovim 0.4.0 or later.
 * Clojure 1.8 or later.
 ** 1.10 or later is recommended.
 * No python! (boost possible with `if_python3`)

== Features

[cols="2*,a"]
|===

|:zap:
|Asynchronous evaluation
|powered by `channel` in Vim8 / Neovim

|:fire:
|Testing
|[%hardbreaks]
Run test under cursor
Run tests in namespace
Re run failed/last test
Also supports https://github.com/lambdaisland/kaocha[kaocha] by https://github.com/liquidz/vim-iced-kaocha[vim-iced-kaocha]

|:rocket:
|Refactoring
|[%hardbreaks]
Clean namespace
Add missing
Thread first/last
Extract function
Move to let
Rename symbol

|:thought_balloon:
|Auto completion
|[%hardbreaks]
Provided by following external plugins.
- https://github.com/liquidz/vim-iced-coc-source[vim-iced-coc-source] for https://github.com/neoclide/coc.nvim[coc.nvim]
- https://github.com/liquidz/vim-iced-asyncomplete[vim-iced-asyncomplete] for https://github.com/prabirshrestha/asyncomplete.vim[asyncomplete.vim]
- https://github.com/tami5/vim-iced-compe[vim-iced-compe] for https://github.com/hrsh7th/nvim-compe[nvim-compe]
Omni completion is provided by default.

|:triangular_ruler:
|Formatting
|[%hardbreaks]
Supports followings currently.
- https://github.com/weavejester/cljfmt[cljfmt] via nREPL
- https://github.com/greglook/cljstyle[cljstyle]
- https://github.com/kkinnear/zprint[zprint]

|:mag:
|Reference
|[%hardbreaks]
Docs, Javadoc, and https://clojuredocs.org[ClojureDocs] https://twitter.com/uochan/status/1154792252167741440[:movie_camera:]
Function dependencies and references https://twitter.com/uochan/status/1139540878853206017[:movie_camera:]

|:ant:
|Debugging
|[%hardbreaks]
Supports cider-nrepl's debugger https://twitter.com/uochan/status/1034404572368842752[:movie_camera:]
Browsing tapped values https://twitter.com/uochan/status/1146982101662572544[:movie_camera:]

|:notebook:
|Skeleton
|Provides code skeleton when you open new file

|:tophat:
|ClojureScript support
|[%hardbreaks]
Supports followings currently.
- https://github.com/bhauman/figwheel-main[Figwheel Main], https://github.com/bhauman/lein-figwheel[lein-figwheel]
- https://github.com/thheller/shadow-cljs[shadow-cljs]

|:electric_plug:
|Socket REPL
|Supports minimal operations.

|:art:
|Command palette
|Access commands smoothly and define user custom commands

|===

NOTE: vim-iced is heavily powered by https://github.com/clojure-emacs/cider-nrepl[cider-nrepl],
https://github.com/clojure-emacs/refactor-nrepl[refactor-nrepl],
and https://github.com/liquidz/iced-nrepl[iced-nrepl].

== Documents

* https://liquidz.github.io/vim-iced/#installation[Installation]
* https://liquidz.github.io/vim-iced/#quick_start[Quick start]
** https://liquidz.github.io/vim-iced/#cheatsheet[Cheatsheet]
* https://liquidz.github.io/vim-iced/vim-iced.html[vim-iced.txt (Vim help file)]

== External plugins

[cols="2*,a"]
|===

|:fire:
| https://github.com/liquidz/vim-iced-kaocha[vim-iced-kaocha]
| Provides some commands for testing with https://github.com/lambdaisland/kaocha[kaocha].


.2+|:mag:
| https://github.com/liquidz/vim-iced-project-namespaces[vim-iced-project-namespaces]
| Provides `:IcedBrowseNamespace` command for jumping to namespace in your project.

| https://github.com/liquidz/vim-iced-function-list[vim-iced-function-list]
| Provides `:IcedBrowseFunction` command for jumping to functions in current namespace.

.3+|:thought_balloon:
| https://github.com/liquidz/vim-iced-coc-source[vim-iced-coc-source]
| Provides auto completion by https://github.com/neoclide/coc.nvim[coc.nvim].

| https://github.com/liquidz/vim-iced-asyncomplete[vim-iced-asyncomplete]
| Provides auto completion by https://github.com/prabirshrestha/asyncomplete.vim[asyncomplete.vim].

| https://github.com/nbardiuk/vim-iced-ncm2[vim-iced-ncm2]
| Provides auto completion by https://github.com/ncm2/ncm2[ncm2].

|:ant:
| https://github.com/liquidz/vim-iced-fern-debugger[vim-iced-fern-debugger]
| Provides tree views for debugging results and tapped values by https://github.com/lambdalisue/fern.vim[fern.vim].

|===

== License

Copyright (c) 2018-2020 http://twitter.com/uochan[Masashi Iizuka]

Distributed under the MIT License.
