=== ClojureDocs

https://clojuredocs.org[ClojureDocs] is a community-powered documentation and examples repository for the Clojure programming language.
Vim-iced can display ClojureDocs reference information for a provided search term or the symbol under the cursor. It opens a temporary
window split which can be closed with {help_html}#%3AIcedDocumentClose[IcedDocumentClose].

[cols="30,20,50"]
|===
| Command | Default key mapping | Description

| {help_html}#%3AIcedClojureDocsOpen[IcedClojureDocsOpen]
| {plug_iced_clojuredocs_open}
| Open a window, and show documents for the symbol under the cursor.

| {help_html}#%3AIcedClojureDocsRefresh[IcedClojureDocsRefresh]
|
| `IcedClojureDocsOpen` will create a cache file on your local machine. +
If you get an out of date result, you can refresh the cache file with this command.

|===

==== ClojureDocs on ClojureScript

ClojureDocs does not have docs for ClojureScript currently.

But if you would like to use Clojure documentation instead of ClojureScript,
you can use it by enabling {help_html}#g%3Aiced%23clojuredocs%23use_clj_docs_on_cljs[g:iced#clojuredocs#use_clj_docs_on_cljs].
