=== Docstring

There are two ways (explicit and implicit) to refer to a var's docstring.

The explicit way is to execute one of the following commands.

[cols="30,20,50"]
|===
| Command | Default key mapping | Description

| {help_html}#%3AIcedDocumentPopupOpen[IcedDocumentPopupOpen]
| {plug_iced_document_popup_open}
| Shows the docstring for the var under the cursor in a popup window.

| {help_html}#%3AIcedDocumentOpen[IcedDocumentOpen]
|
| Opens a <<document_buffer>>, and shows the docstring in it.

|===

The implicit way is the Auto Document feature.
This feature will automatically display a one-line documentation string on the right of cursor line.
This will be done by https://vim-jp.org/vimdoc-en/autocmd.html#CursorMoved[CursorMoved] / https://vim-jp.org/vimdoc-en/autocmd.html#CursorMovedI[CursorMovedI] auto command and https://vim-jp.org/vimdoc-en/eval.html#timer[timer].

- {help_html}#g%3Aiced_enable_auto_document[g:iced_enable_auto_document]: Enable auto document feature.
- {help_html}#g%3Aiced%23nrepl%23auto%23document_delay[g:iced#nrepl#auto#document_delay]: Define delay time for displaying auto document.

