=== Stdout buffer [[stdout_buffer]]

When evaluating a form the output from Clojure's standard output is sent to a dedicated buffer.
Vim-iced provides the following commands to control it's stdout buffer.

[cols="30,20,50"]
|===
| Command | Default key mapping | Description

| {help_html}#%3AIcedStdoutBufferToggle[IcedStdoutBufferToggle]
| {plug_iced_stdout_buffer_toggle}
| Open stdout buffer.

| {help_html}#%3AIcedStdoutBufferOpen[IcedStdoutBufferOpen]
| {plug_iced_stdout_buffer_open}
| Open stdout buffer.

| {help_html}#%3AIcedStdoutBufferClear[IcedStdoutBufferClear]
| {plug_iced_stdout_buffer_clear}
| Clear all lines in stdout buffer.

| {help_html}#%3AIcedStdoutBufferClose[IcedStdoutBufferClose]
| {plug_iced_stdout_buffer_close}
| Close stdout buffer window.

|===

==== Notification

In addition to the stdout buffer, standard output can be displayed on popup notification when stdout buffer is invisible.
If you don't use notification for standard output, see {help_html}#g%3Aiced%23buffer%23stdout%23enable_notify[g:iced#buffer#stdout#enable_notify] option.

See also {help_html}#vim-iced-notification[vim-iced-notification] for more information.

==== Delimiters

It is useful to have a delimited line in the unit of output to limit the range of what you want to see.

See {help_html}#g%3Aiced%23buffer%23stdout%23enable_delimiter[g:iced#buffer#stdout#enable_delimiter] for more information.

