=== Hook [[hook]]

Some events on vim-iced can be hooked, and you can execute any processing.


{help_html}#g%3Aiced%23hook[g:iced#hook] is the definition.
This is a dictionary with hook event as a key,
and the value is a dictionary or a list of dictionaries.

.Definition example
[source,vim]
----
let g:iced#hook = {
    \ 'connected': {'type': 'function',
    \               'exec': {_ -> iced#message#info_str('foo')}},
    \ 'disconnected': [{'type': 'command',
    \                   'exec': 'echom "bar"'}],
    \ 'ns_required': {'type': 'eval',
    \                 'exec': '(println "baz")'},
    \ 'test_finished': {'type': 'shell',
    \                   'exec': {v -> printf('tmux display-message "%s"', v.summary)}}
    \ }
----

Another way, you can also use `iced#hook#add` function to add definitions.

[source,vim]
----
call iced#hook#add('disconnected', {
      \ 'type': 'command',
      \ 'exec': 'echom "hello"',
      \ })
----

==== Event [[hook_event]]

Following events can be hooked.

[cols="20,30,50"]
|===
| Event key | Event parameters | Description

| connected
| -
| Hooked when vim-iced is connected to nREPL.

| disconnected
| -
| Hooked when vim-iced is disconnected from nREPL.

| test_finished
| `result`: Test result ("succeeded" or "failed") +
`summary`: Test summary string
| Hooked when running test is finished.

| ns_required
| -
| Hooked when `:IcedRequire` is finished.

| ns_all_reloaded
| -
| Hooked when `:IcedRequireAll` is finished.

| session_switched
| `session`: Destination session type. "clj" or "cljs".
| Hooked when current session is switched.

| eval_prepared
| `code`: The code to be evalated. +
`option`: Evaluation option.
| Hooked before the start of evaluation. +
The `option` parameter contains `id`, `file`, `line`, `column`, `verbose` and so on.

| evaluated
| `result`: Result map respnsed by nREPL server. +
`option`: Evaluation option.
| Hooked after evaluation. +

The `result` parameter contains `id`, `status`, `ns`, `value` and so on. +
The `option` parameter contains `line`, `column`, `verbose`, `code` and so on.

|===

==== Reporter [[hook_reporter]]

Hooked events and event parameters are reported to reporters.
You can define some kind of reporters as follows.

[cols="30,70"]
|===
| Reporter key | Description

| shell
| Process a event by a shell command. +
The shell command is executed in https://vim-jp.org/vimdoc-en/terminal.html[terminal].

| eval
| Process a event by {help_html}#%3AIcedEval[IcedEval] command.

| function
| Process a event by a user-defined function.

| command
| Process a event by a vim command.

|===
