#!/bin/bash

for i in {1..5}; do
  echo "Trying to deploy: ${i}"

  netlify deploy \
    --auth=${NETLIFY_PERSONAL_ACCESS_TOKEN} \
    --site=${NETLIFY_SITE_ID} \
    --dir=target/html \
    --prod

  if [ $? -eq 0 ]; then
    echo "Succeeded to deploy"
    exit 0
  fi

  sleep 5
done

echo "Failed to deploy"
exit 1
