== Cheatsheet [[cheatsheet]]

[NOTE]
====
Based on default key mappings. +
See {help_html}#g%3Aiced_enable_default_key_mappings[help file] for whole default key mappings.
====

[cols="33a,33a,33a"]
|===

| *Connection*
[cols="30,70"]
!===
! {plug_iced_connect}
! Make connection to nREPL
!===

*<<formatting>>*
[cols="30,70"]
!===
! {plug_iced_format}
! Reformat the form under cursor
!===


| *<<evaluation>>*
[cols="30,70"]
!===
! {plug_iced_eval_outer_list}
! Evaluate outer list
! {plug_iced_eval_outer_top_list}
! Evaluate outer top list
! {plug_iced_require}
! Require current namespace
! {plug_iced_interrupt}
! Interrupt code evaluation
! {plug_iced_refresh}
! Reload all changed files
!===

| *<<macro>>*
[cols="30,70"]
!===
! {plug_iced_macroexpand_1_outer_list}
! Evaluate `macroexpand-1` for outer list
! {plug_iced_macroexpand_outer_list}
! Evaluate `macroexpand` for outer list
!===

| *<<testing>>*
[cols="30,70"]
!===
! {plug_iced_test_under_cursor}
! Run test under cursor
! {plug_iced_test_ns}
! Run tests in current namespace
! {plug_iced_test_redo}
! Re run failed tests
! {plug_iced_test_rerun_last}
! Re run last test
! {plug_iced_test_all}
! Run all tests
!===

| *<<navigation>>*
[cols="30,70"]
!===
! `<C-]>`
!  Jump cursor to the definition of symbol under cursor
! `<C-t>`
! Jump back cursor
! {plug_iced_browse_related_namespace}
! Browse namespaces related to the current namespace
!===

| *<<reference>>*
[cols="30,70"]
!===
! {plug_iced_document_popup_open}
! Show documents for the symbol under cursor
! {plug_iced_source_popup_show}
! Show source for the symbol under cursor
! {plug_iced_document_close}
! Close document buffer
! {plug_iced_browse_spec}
! Browse specs
!===

| *<<refactoring>>*
[cols="30,70"]
!===
! {plug_iced_clean_ns}
! Clean namespace
! {plug_iced_add_ns}
! Add https://clojuredocs.org/clojure.core/ns[`ns`] to require form
! {plug_iced_add_missing}
! Add missing libspec
! {plug_iced_extract_function}
! Extract the form under cursor as a function
! {plug_iced_add_arity}
! Add another arity
! {plug_iced_thread_first}
! Convert form to use https://clojuredocs.org/clojure.core/-%3E[`+->+`] threading macro.
! {plug_iced_thread_last}
! Convert form to use https://clojuredocs.org/clojure.core/-%3E%3E[`+->>+`] threading macro
! {plug_iced_move_to_let}
! Move the form under cursor to nearest https://clojuredocs.org/clojure.core/let[`let`] binding
! {plug_iced_rename_symbol}
! Rename all occurrences of the symbol under cursor.
!===

| *Others*
[cols="30,70"]
!===
! {plug_iced_command_palette}
! Show command palette
!===

|

// End of cheatsheet
|===
