== Formatting [[formatting]]

vim-iced's code formatting is powered by https://github.com/weavejester/cljfmt[cljfmt].
vim-iced proivdes the following two commands to format code.

[cols="30,20,50"]
|===
| Command | Default key mapping | Description

| {help_html}#%3AIcedFormat[IcedFormat]
| {plug_iced_format}
| Reformat current form.


| {help_html}#%3AIcedFormatAll[IcedFormatAll]
| {plug_iced_format_all}
| Reformat current buffer.

|===


https://github.com/guns/vim-sexp[vim-sexp] also provides a code formatting function.
If you want to use vim-iced's formatting function, you should define `g:sexp_mappings` as follows.

[source,vim]
----
let g:sexp_mappings = {'sexp_indent': '', 'sexp_indent_top': ''}
----

TIP: See also <<customizing_indent_rules>>

=== Format on writing files [[format_on_writing_files]]

vim-iced also provides following sync commands.

- {help_html}#%3AIcedFormatSync[IcedFormatSync]
- {help_html}#%3AIcedFormatSyncAll[IcedFormatSyncAll]

These commands are useful for formatting on writing files. 
For example, add this to your confirguration to format the current file on write.
[source,vim]
----
aug VimIcedAutoFormatOnWriting
  au!
  " Format whole buffer on writing files
  au BufWritePre *.clj,*.cljs,*.cljc,*.edn execute ':IcedFormatSyncAll'
aug END
----

Add this to your confirguration to format the current form on write.
[source,vim]
----
aug VimIcedAutoFormatOnWriting
  au!
  " Format only current form on writing files
  au BufWritePre *.clj,*.cljs,*.cljc,*.edn execute ':IcedFormatSync'
aug END
----

=== Customize formatter  [[formatting_customize]]

vim-iced also supports following (GraalVM powered) code formatting tools.

- https://github.com/greglook/cljstyle[cljstyle]
- https://github.com/kkinnear/zprint[zprint]
- https://github.com/candid82/joker[joker]

If you change {help_html}#g%3Aiced_formatter[g:iced_formatter] option,
vim-iced will use the tool to format code and calculate indent level.

[NOTE]
====
These tools can be downloaded automatically if you want.
====

=== Auto indenting [[auto_indenting]]

vim-iced provides auto indentation, enabled by default.

The indent level is calculated by the set formatter,
so `cljfmt` formatter which is used by default may lead slow down vim/nvim.

If you don't use vim-iced's auto indentation,
you can disable it through the {help_html}#g%3Aiced_enable_auto_indent[g:iced_enable_auto_indent] variable.

[source,vim]
----
let g:iced_enable_auto_indent = v:false
----
