== iced command [[iced_command]]

vim-iced provides `iced` command to use vim-iced easily.
Main purpose of this command is launching REPL with all features for vim-iced.

=== Supports [[iced_supports]]

`iced` command currently supports following tools.

- https://github.com/technomancy/leiningen[Leiningen]
- https://github.com/boot-clj/boot[Boot]
- https://clojure.org/guides/deps_and_cli[Clojure CLI]
- https://github.com/thheller/shadow-cljs[shadow-cljs]
-- See also <<clojurescript_shadow_cljs, shadow-cljs section>>.

[WARNING]
====
The `iced` command will automatically search project files (such as "project.clj", "shadow-cljs.edn" and etc) and launch the appropriate REPL for the project.

When multiple projects are found, *the priority is given in the order listed above*.

If you want to specify project type, use `--force-X` option as below.
====

=== Usage [[iced_usage]]

[source,shell]
----
$ iced repl [options]
----

==== Options

Following options are specially treated by `iced` command.

[cols="30,70a"]
|===
| Option | Description

| `--with-cljs`
| Enables ClojureScript features. +
This option is enabled automatically when project configuration +
file(eg. project.clj) contains 'org.clojure/clojurescript' dependency.
[NOTE]
====
By default, it may be a false positive because of simple string match.

In this case, you can use more accurate checks with
https://github.com/borkdude/babashka[Babashka].
(Optional and Limited for Leiningen and Clojure CLI only)
`iced` command will use it automatically when `bb` command exists.
====

| `--with-kaocha`
| Enables features for testing with kaocha.

| `--force-boot`
| Force to use Boot.

| `--force-clojure-cli`
| Force to use Clojure CLI.

| `--force-shadow-cljs`
| Force to use shadow-cljs.

| `--dependency=VALUE`
| Adds extra dependency. +
`VALUE` format is 'PACKAGE_NAME:VERSION'. +
For example: `--dependency=iced-nrepl:0.4.3`

| `--middleware=VALUE`
| Adds extra nrepl middleware. +
For example: `--middleware=iced.nrepl/wrap-iced`

| `--instant`
| Launch instant REPL via Clojure CLI. +
Instant REPL requires no project/config file.

|===

Other options are passed to each program as below.

==== Arguments [[iced_arguments]]

.Leiningen profile
[source,shell]
----
$ iced repl with-profile +foo
----

.Clojure CLI alias
[source,shell]
----
$ iced repl -A:foo
----

.Combinating several options
[source,shell]
----
$ iced repl --with-cljs --force-clojure-cli -A:foo
----

=== Advanced [[iced_command_advanced]]

==== Clojure CLI project

`iced` command use `clj` command for Clojure CLI project by default.

If you would like to use `clojure` command instead, you can overwrite the command by `ICED_REPL_CLOJURE_CLI_CMD` environmental variable.

[source,shell]
----
$ ICED_REPL_CLOJURE_CLI_CMD=clojure iced repl
----

For example, this is useful when you'd like to use https://github.com/bhauman/rebel-readline[rebel-readline] in the REPL which is started by `iced repl`.

