== Reference [[reference]]

=== Docstring

There are two ways (explicit and implicit) to refer var's docstring.

The explicit way is executing commands such as follows.

[cols="30,20,50"]
|===
| Command | Default key mapping | Description

| {help_html}#%3AIcedPopupDocumentOpen[IcedPopupDocumentOpen]
| {plug_iced_popup_document_open}
| Show docstring for the var under the cursor in popup window

| {help_html}#%3AIcedDocumentOpen[IcedDocumentOpen]
|
| Open a <<document_buffer>>, and show docstring in it.

|===

The implicit way is a Auto Document feature.
This feature enable automatic displaying one-line document at right of cursor line.
This will be done by `CursorHold` and `CursorHoldI` auto command.

{help_html}#g%3Aiced_enable_auto_document[g:iced_enable_auto_document] is a configuration to enable auto document feature.

=== ClojureDocs

https://clojuredocs.org[ClojureDocs] is a community-powered documentation and examples repository for the Clojure programming language.
vim-iced provides the way to refer documents in ClojureDocs like docstring.

[cols="30,20,50"]
|===
| Command | Default key mapping | Description

| {help_html}#%3AIcedClojureDocsOpen[IcedClojureDocsOpen]
| {plug_iced_clojuredocs_open}
| Open a window, and show documents for the symbol under the cursor.

| {help_html}#%3AIcedClojureDocsRefresh[IcedClojureDocsRefresh]
|
| `IcedClojureDocsOpen` will create a cache file in your local machine. +
If you get a outdated result, you can refresh cache file by this command.

|===

=== Source codes

{help_html}#%3AIcedSourceShow[IcedSourceShow] or {help_html}#%3AIcedPopupSourceShow[IcedPopupSourceShow] is useful when you would like to refer the source code itself.

// `IcedSourceShow` will open a separeted buffer and show source codes in it, while `IcedPopupSourceShow` shows in a popup window.
// Default key mapping is a `{plug_iced_source_show}` for `IcedSourceShow` and `{plug_iced_popup_source_show}` for `IcedPopupSourceShow`.

[cols="30,20,50"]
|===
| Command | Default key mapping | Description

| {help_html}#%3AIcedPopupSourceShow[IcedPopupSourceShow]
| {plug_iced_popup_source_show}
| Show source codes in a popup window.

| {help_html}#%3AIcedSourceShow[IcedSourceShow]
| {plug_iced_source_show}
| Open a separeted buffer(<<document_buffer>>) and show source codes in it.

|===

=== Use cases

Sometimes, it is useful to know how a function is used elsewhere.
{help_html}#%3AIcedUseCaseOpen[IcedUseCaseOpen] command is for that.

`IcedUseCaseOpen` will open a separated buffer, and show the first usecase if it is found.
When there are several usecases, {help_html}#%3AIcedNextUseCase[IcedNextUseCase] and {help_html}#%3AIcedPrevUseCase[IcedPrevUseCase] commands switch the shown usecase.
