== Reference [[reference]]

=== Docstring

There are two ways (explicit and implicit) to refer var's docstring.

The explicit way is a command such as {help_html}#%3AIcedDocumentOpen[IcedDocumentOpen] and {help_html}#%3AIcedPopupDocumentOpen[IcedPopupDocumentOpen].
Default key mapping is a `{plug_iced_popup_document_open}` to `IcedPopupDocumentOpen` command.

The implicit way is a Auto Document feature.
This feature enable automatic displaying one-line document at right of cursor line.
This will be done by `CursorHold` and `CursorHoldI` auto command.

{help_html}#g%3Aiced_enable_auto_document[g:iced_enable_auto_document] is a configuration to enable auto document feature.

=== ClojureDocs

https://clojuredocs.org[ClojureDocs] is a community-powered documentation and examples repository for the Clojure programming language.
vim-iced provides the way to refer documents in ClojureDocs like docstring.

{help_html}#%3AIcedClojureDocsOpen[IcedClojureDocsOpen] will open a window, and show documents for the symbol under the cursor.
Default key mapping is a `{plug_iced_clojuredocs_open}`.

`IcedClojureDocsOpen` will create a cache file in your local machine.
If you get a outdated result, you can refresh cache file by {help_html}#%3AIcedClojureDocsRefresh[IcedClojureDocsRefresh] command.

=== Source codes

{help_html}#%3AIcedSourceShow[IcedSourceShow] or {help_html}#%3AIcedPopupSourceShow[IcedPopupSourceShow] is useful when you would like to refer the source code itself.

`IcedSourceShow` will open a separeted buffer and show source codes in it, while `IcedPopupSourceShow` shows in a popup window.
Default key mapping is a `{plug_iced_source_show}` for `IcedSourceShow` and `{plug_iced_popup_source_show}` for `IcedPopupSourceShow`.

=== Use cases

Sometimes, it is useful to know how a function is used elsewhere.
{help_html}#%3AIcedUseCaseOpen[IcedUseCaseOpen] command is for that.

`IcedUseCaseOpen` will open a separated buffer, and show the first usecase if it is found.
When there are several usecases, {help_html}#%3AIcedNextUseCase[IcedNextUseCase] and {help_html}#%3AIcedPrevUseCase[IcedPrevUseCase] commands switch the shown usecase.
