=== shadow-cljs [[clojurescript_shadow_cljs]]

To start CLJS REPL with shadow-cljs, you need following steps.

[WARNING]
====
`iced` command uses the existence of `shadow-cljs.edn` file for detecting shadow-cljs project for now.
Thus, if you are using shadow-cljs via Leiningen, you need to setup manually (c.f. {help_html}#vim-iced-manual-shadow-cljs[Manual Install])
instead of the following steps.
====

1. Start to watch
** `$ iced repl {YOUR-BUILD-ID}`
*** In this case, `iced` command will start watching project instead of starting REPL.
*** You need a https://shadow-cljs.github.io/docs/UsersGuide.html#nREPL[nREPL configuration file] to start watching, but `iced` command can generate it automatically.
2. Access shadow-cljs's HTTP server in your browser
** E.g. http://localhost:8080
3. Connect to nREPL
** Execute {help_html}#%3AIcedConnect[IcedConnect] command to connect to REPL
*** For shadow-cljs, cljs-repl will be started automatically after connection.
*** You don't need to specify your build ID anymore.

If you would like to start CLJS REPL by hand, you can do it as follows.
[source,vim]
----
:IcedEvalRepl (shadow.cljs.devtools.api/repl :YOUR-BUILD-ID)
----
